### ISSUE TITLE
Requirement of redis 4.x isn't enforced

### ISSUE THREAD

**Issue by jgeiger** [sds/mock_redis#169]
More of a comment for people updating the gem, but it seems like even though there's "development" dependency on redis 4.x, it's not required when including this gem in other projects.

This will cause an issue since it still installs, but specs will fail.

**Comment by sds** [comment]
Thanks for the heads up!

Closing as informational as there are situations where you can still use Mock Redis without requiring Redis 4.x, which is why we didn't want to make it a hard requirement. Perhaps that's the wrong choice, but we wanted to allow developers to make that tradeoff decision themselves.

If there's a clear reason to always require this, we're open to making it a hard dependency. You can always specify an explicit dependency in your own project, if you so choose.
