### ISSUE TITLE
Not mention XADD was supported for this gem, right?

### ISSUE THREAD

**Issue by zw963** [sds/mock_redis#237]

**Comment by sds** [comment]
A [quick search](https://github.com/sds/mock_redis/search?q=xadd) indicates there is an `xadd` method implemented. How complete that implementation I don't believe is captured anywhere (and since it was contributed externally, you'd have to ask the original contributor). 

If it is missing functionality, please open a pull request to add the desired functionality. Thank you.

**Comment by zw963** [comment]
Sorry, what i means is i know xadd was support, in fact, i use this gem for this feature. (not all gem support it, e.g. fakeredis not support it)

This issue is just for we should mention we support xadd in https://github.com/sds/mock_redis#supported-features
