### ISSUE TITLE
ArgumentError after update ruby from 3.1.2 to 3.2.0

### ISSUE THREAD

**Issue by dmytro-korzhov-rg** [sds/mock_redis#266]
Hi!
sorry for the misunderstanding on my part, I'm a newbie
I ran into this problem after updating:
`(rdbg) redis`
`#<MockRedis:0x00007ff15f391f18`
` @db=`
`  #<MockRedis::PipelinedWrapper:0x00007ff15f90faf8`
`   @db=`
`    #<MockRedis::TransactionWrapper:0x00007ff15f222a38`
`     @db=`
`      #<MockRedis::ExpireWrapper:0x00007ff15f90fe18`
`       @db=`
`        #<MockRedis::MultiDbWrapper:0x00007ff15f3912e8`
`         @databases={0=>#<MockRedis::Database:0x00007ff15f391608 @base=#<MockRedis:0x00007ff15f391f18 ...>, @data={}, @expire_times=[]>},`
`         @db_index=0,`
`         @prototype_db=#<MockRedis::Database:0x00007ff15f391248 @base=#<MockRedis:0x00007ff15f391f18 ...>, @data={}, @expire_times=[]>>>,`
`     @multi_block_given=false,`
`     @multi_stack=[],`
`     @transaction_futures=[]>,`
`   @nesting_level=0,`
`   @pipelined_futures=[]>,`
` @options={:scheme=>"redis", :host=>"127.0.0.1", :port=>6379, :path=>nil, :timeout=>5.0, :password=>nil, :logger=>nil, :db=>0, :time_class=>Time}>`

`redis.set("stripe-connect:1", "SecureCode123", ex: 86400)`
`eval error: wrong number of arguments (given 3, expected 2)`
`  /usr/local/bundle/gems/mock_redis-0.36.0/lib/mock_redis/string_methods.rb:215:in "set"`

can you suggest a solution? Everything works fine with the adapter.

**Comment by dmytro-korzhov-rg** [comment]
but I send 2 argument and ex: (key, value, ex:)

**Comment by Umofomia** [comment]
It looks like this is due to the Ruby 3 [separation of positional and keyword arguments](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

`mock_redis` defines a `set` method with keyword arguments here:
https://github.com/sds/mock_redis/blob/8b0180708a67402c2d453a837bb4e816851944d0/lib/mock_redis/string_methods.rb#L215

However, `redis-store` itself [consistently never uses keyword arguments in its definition of `set`](https://github.com/search?q=repo%3Aredis-store%2Fredis-store+%22def+set%22&type=code). Instead, it generally defines `set` as:

```ruby
def set(key, value, options = nil)
```

Because of this, Ruby 3 ends up interpreting `redis-store`'s call into `mock_redis` as sending 3 arguments [here](https://github.com/redis-store/redis-store/blob/v1.9.2/lib/redis/store/ttl.rb#L8):

```ruby
super(key, value, options)
```

@sds It looks like #196 introduced keyword arguments to `mock_redis`. It looks like that change may need to be backed out in some way in order for `mock_redis` to support Ruby 3.

**Comment by sds** [comment]
Given [Ruby 2.7 reached EOL in March 2023](https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/), I'm very supportive of a PR that removes support for Ruby 2.x, fixing this in the process.

**Comment by Umofomia** [comment]
Hmm... looking into this further, it's only with the inclusion of the `redis-store` gem where this is an issue, because the `redis` gem itself does [use keyword arguments for `set`](https://github.com/redis/redis-rb/blob/1f370951ab0dab830461f36da67a93dbc1aabd6d/lib/redis/commands/strings.rb#L83):

```ruby
      def set(key, value, ex: nil, px: nil, exat: nil, pxat: nil, nx: nil, xx: nil, keepttl: nil, get: nil)
```

For this reason, I'm now thinking that the fix should actually be in `redis-store` instead.
